name: "conpair_concordance"
description: Conpair concordance and contamination assessment
keywords:
  - conpair
  - concordance
  - contamination
  - sample-quality
tools:
  - conpair:
      description: Concordance and contamination assessment
      homepage: "https://github.com/mskcc/conpair"
      documentation: "https://github.com/mskcc/conpair"
      licence: ["MIT"]
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', tumor_id:'tumor1', normal_id:'normal1' ]`
  - - tumor_pileup:
        type: file
        description: Tumor pileup file
        pattern: "*.pileup"
  - - normal_pileup:
        type: file
        description: Normal pileup file
        pattern: "*.pileup"
output:
  - concordance:
    - - meta:
          type: map
          description: Sample metadata
    - - "*.concordance.tsv":
          type: file
          description: Concordance assessment results
          pattern: "*.concordance.tsv"
  - contamination:
    - - meta:
          type: map
          description: Sample metadata
    - - "*.contamination.tsv":
          type: file
          description: Contamination assessment results
          pattern: "*.contamination.tsv"
  - versions:
    - - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@mskcc"
maintainers:
  - "@mskcc"
