#!/bin/bash
# NEXTFLOW TASK: AlignReads (1234-9876T)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a ALL_CHILD
    while read P PP;do
        ALL_CHILD[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    walk() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${ALL_CHILD[$1]:=}; do walk $i; done
    }

    walk $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /Users/biederse/vaporware/work/3d/8ae1184888a3873b02501917886865/.exitcode
  set +u
  [[ "$tee1" ]] && kill $tee1 2>/dev/null
  [[ "$tee2" ]] && kill $tee2 2>/dev/null
  [[ "$ctmp" ]] && rm -rf $ctmp || true
  docker rm $NXF_BOXID &>/dev/null || true
  exit $exit_status
}

on_term() {
    set +e
    docker kill $NXF_BOXID
}

trap on_exit EXIT
trap on_term TERM INT USR1 USR2

export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A)"
NXF_SCRATCH=''
[[ $NXF_DEBUG > 0 ]] && nxf_env
touch /Users/biederse/vaporware/work/3d/8ae1184888a3873b02501917886865/.command.begin
# task environment
nxf_taskenv() {
cat << EOF
export NXF_OPTS="-Xms10g"
EOF
}

[[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
# stage input files
rm -f input.1
rm -f C09D_T_111207.6.ACCAACTG_R1_xxx.fastq.gz
rm -f human_g1k_v37_decoy.small.fasta
rm -f human_g1k_v37_decoy.small.fasta.amb
rm -f human_g1k_v37_decoy.small.fasta.bwt
rm -f human_g1k_v37_decoy.small.fasta.pac
rm -f human_g1k_v37_decoy.small.fasta.ann
rm -f human_g1k_v37_decoy.small.fasta.sa
ln -s /Users/biederse/vaporware/work/tmp/31/6df4ba318ad7e8e4419e73710116ec/input.1 input.1
ln -s /Users/biederse/pipeline_development/Sarek_revisions_25Jan2019/Sarek-data/testdata/manta/tumor/C09D_T_111207.6.ACCAACTG_R1_xxx.fastq.gz C09D_T_111207.6.ACCAACTG_R1_xxx.fastq.gz
ln -s /Users/biederse/pipeline_development/Sarek_revisions_25Jan2019/References/smallGRCh37/human_g1k_v37_decoy.small.fasta human_g1k_v37_decoy.small.fasta
ln -s /Users/biederse/pipeline_development/Sarek_revisions_25Jan2019/References/smallGRCh37/human_g1k_v37_decoy.small.fasta.amb human_g1k_v37_decoy.small.fasta.amb
ln -s /Users/biederse/pipeline_development/Sarek_revisions_25Jan2019/References/smallGRCh37/human_g1k_v37_decoy.small.fasta.bwt human_g1k_v37_decoy.small.fasta.bwt
ln -s /Users/biederse/pipeline_development/Sarek_revisions_25Jan2019/References/smallGRCh37/human_g1k_v37_decoy.small.fasta.pac human_g1k_v37_decoy.small.fasta.pac
ln -s /Users/biederse/pipeline_development/Sarek_revisions_25Jan2019/References/smallGRCh37/human_g1k_v37_decoy.small.fasta.ann human_g1k_v37_decoy.small.fasta.ann
ln -s /Users/biederse/pipeline_development/Sarek_revisions_25Jan2019/References/smallGRCh37/human_g1k_v37_decoy.small.fasta.sa human_g1k_v37_decoy.small.fasta.sa

set +e
ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
cout=$ctmp/.command.out; mkfifo $cout
cerr=$ctmp/.command.err; mkfifo $cerr
tee .command.out < $cout &
tee1=$!
tee .command.err < $cerr >&2 &
tee2=$!
(
docker run -i --memory 20480m -v /Users/biederse:/Users/biederse -v "$PWD":"$PWD" -w "$PWD" --entrypoint /bin/bash -u $(id -u):$(id -g) --name $NXF_BOXID quay.io/collaboratory/dockstore-tool-bwa-mem:1.0 -c "eval $(nxf_taskenv); /bin/bash -ue /Users/biederse/vaporware/work/3d/8ae1184888a3873b02501917886865/.command.sh"
) >$cout 2>$cerr &
pid=$!
wait $pid || ret=$?
wait $tee1 $tee2
