name: Branch checks
on:
  pull_request:
    branches: [main]

jobs:
  branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        if: github.repository == 'mskcc/tempo'
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" != "dev" ]; then
            echo "::error::PRs to main must come from dev branch"
            exit 1
          fi
