name: nf-core linting
on:
  push:
    branches: [main, dev, 'nf-core/**']
  pull_request:
    branches: [main, dev]

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check .

  nf-core-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install nf-core tools
        run: pip install nf-core
      - name: Run nf-core lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nf-core -l lint_log.txt pipelines lint --dir . --fail-warned
      - name: Upload lint log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-log
          path: lint_log.txt
